services:
  - type: web
    name: websocket-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
