services:
  - type: web
    name: websocket-server
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --worker-class gevent -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
